project:
  type: website
  output-dir: docs

website:
  title: "Stephen Min"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css
    toc: true

editor: visual

