---
title: "Portfolio"
subtitle: "My projects and analyses are displayed here. I mainly focus on economic topics, and the coding is done primarily with R and Python."
title-block-banner: true
bibliography: references.bib
---

# Quantifying Heterogeneity of Discrimination in the Canadian Labor Market

This is a mini-research paper that was done as my capstone project for my MA in economics at Simon Fraser University; we were given 4 months to develop a research question and write a paper answering it.

I applied a causal machine learning algorithm (causal forest) to a dataset from @oreopoulos2011 that contains information on artificial resumes that were sent out to Canadian employers roughly 10 years ago. I used various transformations and visualizations of the algorithm outputs to quantify how different groups of minorities are impacted by discrimination in the labor market.

[Link to paper {{< fa link >}}](files/899_Paper.pdf){.btn .btn-outline-primary} [Source code {{< fa brands github >}}](https://github.com/TopologicalDonut/Masters-Paper){.btn .btn-outline-primary}

# ONS Item-Level CPI Data Pipeline

This is a Python-based ETL pipeline for automating the collection and processing of item-level consumer price index (CPI) data from the UK's Office for National Statistics (ONS).

The pipeline scrapes all the files and zips that contain data on price indices, processes the data using Polars, and stores it into a local DuckDB database.

[Source Code {{< fa brands github >}}](https://github.com/TopologicalDonut/ONS-pipeline){.btn .btn-outline-primary}

# UK Tax Policy Analysis

This is an analysis of how the 2021 UK tampon tax abolition affected tampon prices using an event study. I queried the database made by the ONS Pipeline to get relevant data and used a regression with ARIMA errors to account for the time series nature of price data.

[Link to report {{< fa link >}}](files/UK_Report.pdf){.btn .btn-outline-primary} [Source code {{< fa brands github >}}](https://github.com/TopologicalDonut/UK-Tax-Analysis){.btn .btn-outline-primary}

# Vancouver Crime Analysis

This is an analysis of how daylight savings time (DST) affects crime in Vancouver. Inspired by @doleac2015, I applied a regression discontinuity design with the running variable being days from the start of DST.

[Link to blog post {{< fa link >}}](https://topologicaldonut.github.io/posts/Vancouver_DST/){.btn .btn-outline-primary} [Source code {{< fa brands github >}}](https://github.com/TopologicalDonut/Vancouver-Crime-Analysis){.btn .btn-outline-primary}
